In [1]:
import numpy as np
x = np.random.random((5,5))
x

array([[0.15169301, 0.73170696, 0.55800006, 0.32114369, 0.57822091],
       [0.11197413, 0.41483389, 0.88522591, 0.31799276, 0.82469694],
       [0.13335639, 0.27145745, 0.38473906, 0.85551173, 0.89120308],
       [0.38154901, 0.32090852, 0.3497898 , 0.90880422, 0.82180836],
       [0.65914264, 0.58194171, 0.81151849, 0.98181569, 0.69497744]])

In [2]:
np.save('2d_array',x)


In [3]:
loaded_array=np.load('2d_array.npy')
loaded_array

array([[0.15169301, 0.73170696, 0.55800006, 0.32114369, 0.57822091],
       [0.11197413, 0.41483389, 0.88522591, 0.31799276, 0.82469694],
       [0.13335639, 0.27145745, 0.38473906, 0.85551173, 0.89120308],
       [0.38154901, 0.32090852, 0.3497898 , 0.90880422, 0.82180836],
       [0.65914264, 0.58194171, 0.81151849, 0.98181569, 0.69497744]])

In [4]:
excel.csv.csv


NameError: name 'excel' is not defined

In [5]:
demo.csv


NameError: name 'demo' is not defined

In [8]:
data=np.genfromtext('demo.csv',delimiter=',',names=True)
data

AttributeError: module 'numpy' has no attribute 'genfromtext'

In [11]:
import csv
with open('demo.csv', mode='r')as fl= float(input("enter length in mtre")):
csvFile=csv.reader(file)
for lines in csvFile:
    print(lines)


IndentationError: expected an indented block (Temp/ipykernel_7576/1326997479.py, line 3)

In [13]:
n=int(input("enter a positive number= "))
s=(n*(n+1))/2
print("The sum of all numbers till n is =",s)

enter a positive number= 8
The sum of all numbers till n is = 36.0


In [14]:
l=float(input("enter length in metre= "))
b=float(input("enter width in metre= "))
area=l*b
print("The area is",area,"m")


enter length in metre= 6
enter width in metre= 76
The area is 456.0 m


In [15]:
import numpy as np
a=np.arange(start=1,stop=10,step=2)
a

array([1, 3, 5, 7, 9])

In [16]:
a = np.array("Annie,Bose,Christina,David,Estella,Fred,Gwen,Harry,Damon,Stefan".split(','))
b= list(np.array(('D2,'*10).split(',')))
mark1 =  np.random.randint(100,size=(10,))
mark2 =  np.random.randint(100,size=(10,))
mark3 =  np.random.randint(100,size=(10,))
b.pop()

''

In [17]:
data = np.array([[a],[b],[mark1],[mark2],[mark3]])
data


array([[['Annie', 'Bose', 'Christina', 'David', 'Estella', 'Fred',
         'Gwen', 'Harry', 'Damon', 'Stefan']],

       [['D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2']],

       [['97', '38', '61', '25', '29', '49', '44', '33', '56', '22']],

       [['25', '18', '45', '53', '83', '59', '87', '63', '96', '96']],

       [['94', '30', '80', '91', '52', '99', '44', '59', '62', '94']]],
      dtype='<U11')

In [18]:
data_n = data.reshape(5,10)
data_n.T


array([['Annie', 'D2', '97', '25', '94'],
       ['Bose', 'D2', '38', '18', '30'],
       ['Christina', 'D2', '61', '45', '80'],
       ['David', 'D2', '25', '53', '91'],
       ['Estella', 'D2', '29', '83', '52'],
       ['Fred', 'D2', '49', '59', '99'],
       ['Gwen', 'D2', '44', '87', '44'],
       ['Harry', 'D2', '33', '63', '59'],
       ['Damon', 'D2', '56', '96', '62'],
       ['Stefan', 'D2', '22', '96', '94']], dtype='<U11')

In [19]:
csv_rows = ["{},{},{},{},{}".format(i, j, k,m,n) for i, j, k, m, n in data_n.T]
csv_text = "\n".join(csv_rows)

with open('sample.csv', 'w') as f:
    f.write(csv_text)
    

In [20]:
with open('sample.csv','r') as f:
    txt  = f.readlines()

In [21]:
data = np.genfromtxt('sample.csv',delimiter=",",skip_header=True,dtype =str)
data

array([['Bose', 'D2', '38', '18', '30'],
       ['Christina', 'D2', '61', '45', '80'],
       ['David', 'D2', '25', '53', '91'],
       ['Estella', 'D2', '29', '83', '52'],
       ['Fred', 'D2', '49', '59', '99'],
       ['Gwen', 'D2', '44', '87', '44'],
       ['Harry', 'D2', '33', '63', '59'],
       ['Damon', 'D2', '56', '96', '62'],
       ['Stefan', 'D2', '22', '96', '94']], dtype='<U9')